---
deployment:
  tasks:
    # 1. Path di bawah ini sudah saya sesuaikan dengan struktur folder di gambar Anda
    - export DEPLOYPATH=$HOME/domains/api.achmaddarussalamridho.my.id
    
    # 3. Copy semua file dari git repository ke folder public tujuan
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    
    # 4. Masuk ke folder tujuan dan jalankan instalasi / pembaruan package Laravel
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    
    # (Opsional) Hapus tanda '#' di bawah ini jika Anda ingin otomatis update tabel database (migrate)
    # - php artisan migrate --force
