---
deployment:
  tasks:
    # 1. Path di bawah ini sudah saya sesuaikan dengan struktur folder di gambar Anda
    - export DEPLOYPATH=$HOME/domains/api.achmaddarussalamridho.my.id
    
    # 3. Copy semua file dari git repository ke folder public tujuan
    - /bin/cp -R * $DEPLOYPATH
    # (HAPUS copy .env.example agar tidak menimpa pengaturan database asli server)
    
    # 4. Masuk ke folder tujuan dan jalankan instalasi / pembaruan package Laravel
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    
    # Update tabel database (migrate) secara otomatis
    - php artisan migrate --force
